export const FETCH_ALL_RECIPE_IDS_BEGIN = "FETCH_ALL_RECIPE_IDS_BEGIN"
export const FETCH_ALL_RECIPE_IDS_SUCCESS = "FETCH_ALL_RECIPE_IDS_SUCCESS"
export const FETCH_ALL_RECIPE_IDS_FAILURE = "FETCH_ALL_RECIPE_IDS_FAILURE"

export const FETCH_RECIPE_BEGIN = "FETCH_RECIPE_BEGIN"
export const FETCH_RECIPE_SUCCESS = "FETCH_RECIPE_SUCCESS"
export const FETCH_RECIPE_FAILURE = "FETCH_RECIPE_FAILURE"

export const SEARCH_RECIPES_BEGIN = "SEARCH_RECIPES_BEGIN"
export const SEARCH_RECIPES_SUCCESS = "SEARCH_RECIPES_SUCCESS"
export const SEARCH_RECIPES_FAILURE = "SEARCH_RECIPES_FAILURE"

export const FETCH_ALL_RECIPES_BEGIN = "FETCH_ALL_RECIPES_BEGIN"
export const FETCH_ALL_RECIPES_SUCCESS = "FETCH_ALL_RECIPES_SUCCESS"
export const FETCH_ALL_RECIPES_FAILURE = "FETCH_ALL_RECIPES_FAILURE"
